<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerXtnkkvk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtnkkvk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXtnkkvk.legacy');
=======
if (\class_exists(\ContainerEiz2hgw\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEiz2hgw/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEiz2hgw.legacy');
>>>>>>> f54da581bde2c986560b121ad2f1dc3f2a61cabb

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerXtnkkvk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXtnkkvk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xtnkkvk',
    'container.build_id' => '919019e8',
    'container.build_time' => 1538041057,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtnkkvk');
=======
    \class_alias(\ContainerEiz2hgw\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEiz2hgw\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Eiz2hgw',
    'container.build_id' => '22994c93',
    'container.build_time' => 1538024053,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEiz2hgw');
>>>>>>> f54da581bde2c986560b121ad2f1dc3f2a61cabb
